services:
  stonkfly:
    image: ghcr.io/twindragon97/stonkfly:latest
    container_name: stonkfly

    restart: unless-stopped

    volumes:
      - /DATA/AppData/stonkfly/data:/app/data
      - /DATA/AppData/stonkfly/runs:/app/runs

    environment:
      TZ: Europe/Madrid
      PYTHONUNBUFFERED: "1"

    deploy:
      resources:
        limits:
          memory: 8G
          cpus: "8.0"
        reservations:
          memory: 1G
          cpus: "1.0"
