"""One background paper-only trainer. No arbitrary commands or paths from HTTP."""

import json
import secrets
import subprocess
import sys
import threading
import time
from pathlib import Path

from stonkfly.locking import exclusive
from stonkfly.training import TrainingConfig, atomic_json

ACTIVE = {"starting", "preparing", "downloading", "loading", "training", "evaluating"}


class TrainingJobs:
    def __init__(self, root, runs, cache):
        self.root, self.runs, self.cache = Path(root), Path(runs), Path(cache)
        self.token = secrets.token_urlsafe(32)
        self.lock = threading.RLock()
        self.process = None
        self.job = None
        pointer = self.runs / "latest.json"
        if pointer.exists():
            name = json.loads(pointer.read_text()).get("run", "")
            if name.startswith("train-") and Path(name).name == name and "/" not in name and "\\" not in name:
                self.job = self.runs / name

    def status(self):
        with self.lock:
            if self.job is None:
                return {"state": "idle"}
            path = self.job / "status.json"
            result = json.loads(path.read_text()) if path.exists() else {"state": "starting", "run": self.job.name}
            if result["state"] in ACTIVE:
                exited = self.process is not None and self.process.poll() is not None
                if self.process is None:
                    try:
                        with exclusive(self.runs / "training-worker.lock"):
                            exited = True
                    except RuntimeError:
                        pass
                if exited:
                    result.update(state="failed", message="El proceso terminó sin completar el entrenamiento. Consulta worker.log; usa una sesión nueva.")
                    atomic_json(path, result)
            if result["state"] == "completed":
                # Generated by us, fixed file name; shown as a command, never executed by HTTP.
                import shlex
                result["paper_command"] = ("python -m stonkfly run --memory "
                    + shlex.quote(str(self.job / "memory.npz")) + " --out "
                    + shlex.quote(str(self.runs.parent / ("paper-" + self.job.name))))
            return result

    def start(self, values):
        config = TrainingConfig(**values)
        if config.start_year < 2016:
            raise ValueError("La descarga usa años desde 2016; para otros históricos usa --csv en la CLI")
        with self.lock:
            if self.status()["state"] in ACTIVE:
                raise ValueError("Ya hay un entrenamiento activo")
            self.runs.mkdir(parents=True, exist_ok=True)
            name = "train-" + time.strftime("%Y%m%d-%H%M%S") + "-" + secrets.token_hex(3)
            job = self.runs / name
            job.mkdir()
            args = [sys.executable, "-m", "stonkfly", "train", "--out", str(job), "--cache", str(self.cache)]
            for key in ("start_year", "end_year", "evaluation_year", "interval", "epochs", "neural_ms"):
                args.extend(["--" + key.replace("_", "-"), str(getattr(config, key))])
            with (job / "worker.log").open("wb") as log:
                self.process = subprocess.Popen(args, cwd=self.root, stdout=log, stderr=log,
                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
            self.job = job
            atomic_json(self.runs / "latest.json", {"run": name})
            return {"state": "starting", "run": name}

    def stop(self):
        with self.lock:
            if self.job is None or self.status()["state"] not in ACTIVE:
                raise ValueError("No hay un entrenamiento activo")
            (self.job / "STOP").touch()
            return {"state": "stopping", "message": "Se detendrá al terminar el paso o la descarga actual."}
